### ISSUE TITLE
蹲个可以对话文件的版本

### ISSUE THREAD

**Issue by 3377** [deanxv/genspark2api#2]
目前速度不错诶，希望可以出个对话图片，识别图片，文件的版本。

**Comment by deanxv** [comment]
当前最新版本已可以识图

**Comment by 3377** [comment]
> 当前最新版本已可以识图

大佬牛啊，那不要脸的再求个删除对话id记录的功能，现在api对话后会在页面生成一堆对话记录。。
另外必须要cookie吗？貌似另外一个2api只用sessio_id就可以了。我账号当时忘了记录cookie~现在已经忘记了是哪个机场登录的了。。

**Comment by deanxv** [comment]
> > 当前最新版本已可以识图
> 
> 大佬牛啊，那不要脸的再求个删除对话id记录的功能，现在api对话后会在页面生成一堆对话记录。。 另外必须要cookie吗？貌似另外一个2api只用sessio_id就可以了。我账号当时忘了记录cookie~现在已经忘记了是哪个机场登录的了。。

你只有session_id的话 在GS_COOKIE环境变量中只写'session_id=f9c*****b6d'应该也没问题。删除对话记录的功能已经写好了，现在Genspark官方服务崩了，没办法调试...

**Comment by 3377** [comment]
哈哈哈，笑死了，等好了就弄到hf上去，你要不顺便加个路由的变量。。。hf得加路由

**Comment by deanxv** [comment]
> 哈哈哈，笑死了，等好了就弄到hf上去，你要不顺便加个路由的变量。。。hf得加路由

这个是另外的大佬提供的 [https://huggingface.co/spaces/michally/gxxexxxnxxsxxpxxaxxrkxx2xxaxxpxxi/blob/main/Dockerfile?duplicate=true](https://huggingface.co/spaces/michally/gxxexxxnxxsxxpxxaxxrkxx2xxaxxpxxi/blob/main/Dockerfile?duplicate=true)

**Comment by kaqijiang** [comment]
环境变量能否外部传递，这样可以根据后期封控单独处理渠道

**Comment by deanxv** [comment]
> 环境变量能否外部传递，这样可以根据后期封控单独处理渠道

可以暂时先采用部署多实例，采用oneapi这种管理渠道的方案。

**Comment by kaqijiang** [comment]
> > 环境变量能否外部传递，这样可以根据后期封控单独处理渠道
> 
> 可以暂时先采用部署多实例，采用oneapi这种管理渠道的方案。

但是如果一批号封了几个 这样找起来就太累人了

**Comment by deanxv** [comment]
> > > 环境变量能否外部传递，这样可以根据后期封控单独处理渠道
> 
> > 
> 
> > 可以暂时先采用部署多实例，采用oneapi这种管理渠道的方案。
> 
> 
> 
> 但是如果一批号封了几个 这样找起来就太累人了

oneapi在渠道不可用时也会触发自动禁用和邮件通知，建议一个账号一个渠道。目前确实想不到什么方案在2api里做渠道相关的逻辑，再就是genspark升级了api的风控，所以项目可能过几天就用不了了。
