### ISSUE TITLE
绘图相关模型似乎不支持非流

### ISSUE THREAD

**Issue by nitmali** [deanxv/genspark2api#3]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ✓] 我已确认目前没有类似 issue
+ [✓ ] 我已确认我已升级到最新版本
+ [ ✓] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ✓] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
绘图相关模型似乎不支持非流
**复现步骤**
调用flux传参`stream: false`时还是以流式返回
**预期结果**
以非流式返回
**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
最新版本修复了这个问题 试试

**Comment by nitmali** [comment]
> 最新版本修复了这个问题 试试

测试可以了，效率真高
