### ISSUE TITLE
响应怎么这么慢，要等15秒才开始回答

### ISSUE THREAD

**Issue by nsyncxy1** [deanxv/genspark2api#4]
不知道怎么回事，用的claude3.5模型

**Comment by deanxv** [comment]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/dc286063-2c60-4c85-bb14-0305b5b5b2cd" />
该模式下会增加响应时间

**Comment by alexallen1** [comment]
日后会不会更新用session_id的方式~

**Comment by deanxv** [comment]
> 日后会不会更新用session_id的方式~

<img width="872" alt="image" src="https://github.com/user-attachments/assets/aeb12675-b744-4176-bdce-30cf26707d61" />

只有seesion_id也可以使用。

**Comment by alexallen1** [comment]
@deanxv 是的 图片点开了才知道不是要完整一大段cookie
