### ISSUE TITLE
render部署问题

### ISSUE THREAD

**Issue by gonisan** [deanxv/genspark2api#5]
**温馨提示: 未`star`项目会被自动关闭issue哦!**
**问题描述**
请问下这是什么问题
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/3d8bf094-0e55-404f-b9de-621989812fbc)

**Comment by deanxv** [comment]
Render的ip被cf风控出盾了，可以换个vps部署或者用环境变量`PROXY_URL`启用代理

**Comment by gonisan** [comment]
> Render的ip被cf风控出盾了，可以换个vps部署或者用环境变量`PROXY_URL`启用代理

好的，明白了
