### ISSUE TITLE
在第二轮对话时Claude模型会被替换为其它模型

### ISSUE THREAD

**Issue by majesticdragons** [deanxv/genspark2api#6]
![IMG_20241227_201744](https://github.com/user-attachments/assets/88069c5f-e6dc-4469-8064-e88dbf0c847f)
![IMG_20241227_201831](https://github.com/user-attachments/assets/5295acd7-8383-4088-8021-ca29ec1b457c)

经过多次测试，从第二轮对话开始，genspark2api的Claude模型会被替换为其它模型。
判断方法为：中文对话时，Claude很大概率会使用半角逗号，其它模型会使用全角逗号。

**Comment by deanxv** [comment]
可以在对话后在genspark官网查看下对话记录是否更换了模型

**Comment by majesticdragons** [comment]
看了下官网，貌似对话记录下面显示的是在官网最后一次使用的模型，跟2api里使用了什么模型无关。另外这个问题是我今天才遇到的，而且GS_COOKIE里只填session_id会空回复，要把全部填进去才行。

**Comment by deanxv** [comment]
1. 2api就是官网的逆向接口，2api使用的模型就会在官网显示
2. 官网也并非全是半角，这种方法判断模型不太可靠 
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/a8e40081-2ada-494f-a570-0b9641c88735" />
3. GS_COOKIE并不是只填session_id，而是 `GS_COOKIE=session_id=f9c60******cb6d`
<img width="728" alt="image" src="https://github.com/user-attachments/assets/45fe6630-b003-4778-b34d-27817eeb0513" />

**Comment by majesticdragons** [comment]
感谢解答。
1. 在我这边，2api使用了4o后，官网里确实仍然显示为claude：
![Screenshot_2024-12-27-22-25-17-399_cc arthur63 chatbot-edit](https://github.com/user-attachments/assets/d4999f83-db65-4d90-9beb-2e0c1e02109b)
![IMG_20241227_222439 (1)](https://github.com/user-attachments/assets/b524bfe4-b294-461c-a5c5-2c723f2ed92b)
2. 官网的Claude确实也会使用全角，但我的意思是两边上下文相同的情况下，官网和2api的输出有很大差异：
user：你好
Claude：官网和2api的回复都包含了半角逗号且回复内容一致
user：没有
Claude：官网继续使用使用半角；2api使用全角
3. 不好意思，我表达有误，我想说的是只填“session_id=xxx”会空回复。前几天填的“session_id=xxx”都没有问题，今天空回复了。

这些问题都是今天才出现的，不知道是不是我账号的问题。

**Comment by majesticdragons** [comment]
又试了一下站内的公益api，几乎可以肯定从第二轮开始模型就被替换为4o-mini了。
![1](https://github.com/user-attachments/assets/52cd3693-e137-49aa-bdb0-cc21d579cebc)
![2](https://github.com/user-attachments/assets/c5dacf37-6ea2-4e7f-91cc-778d0938bca3)
![3](https://github.com/user-attachments/assets/05d96462-0b50-4800-ba83-ca0497a4fe4c)
![4](https://github.com/user-attachments/assets/9e89320c-2753-4c21-9f7e-854f64b5b13b)

**Comment by deanxv** [comment]
> 感谢解答。
> 
> 1. 在我这边，2api使用了4o后，官网里确实仍然显示为claude：
>    ![Screenshot_2024-12-27-22-25-17-399_cc arthur63 chatbot-edit](https://private-user-images.githubusercontent.com/192528745/398956392-d4999f83-db65-4d90-9beb-2e0c1e02109b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNTMxNTMsIm5iZiI6MTczNTM1Mjg1MywicGF0aCI6Ii8xOTI1Mjg3NDUvMzk4OTU2MzkyLWQ0OTk5ZjgzLWRiNjUtNGQ5MC05YmViLTJlMGMxZTAyMTA5Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwMjI3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTM2MzFkMTU5MmViMzVjZTRiN2E3ZWJlOGNkZDAzYTUwZmQyNDExYjBiOTU1OWMzMjhlYzg5ZWYxZGZiYzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nnIFMP1CmBas_4x5t2TH8QwcFs-JWJF-JG4IkY7Lb84)
>    ![IMG_20241227_222439 (1)](https://private-user-images.githubusercontent.com/192528745/398956408-b524bfe4-b294-461c-a5c5-2c723f2ed92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNTMxNTMsIm5iZiI6MTczNTM1Mjg1MywicGF0aCI6Ii8xOTI1Mjg3NDUvMzk4OTU2NDA4LWI1MjRiZmU0LWIyOTQtNDYxYy1hNWM1LTJjNzIzZjJlZDkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwMjI3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODk5NGQ4ZTkyN2RlZjAyMjYzMDU1ZWI4MjYxMzM1ZDVmZTc0YjJhY2ZkZmE5MWZhOTY3MzZmNTNhY2U0YjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PoIRPLHnK5skMflhXg20wCfUCImV7_mk-s_TfTIa_B4)
> 2. 官网的Claude确实也会使用全角，但我的意思是两边上下文相同的情况下，官网和2api的输出有很大差异：
>    user：你好
>    Claude：官网和2api的回复都包含了半角逗号且回复内容一致
>    user：没有
>    Claude：官网继续使用使用半角；2api使用全角
> 3. 之前的value部分一直填的“session_id=xxx”没有问题，今天就空回复了。
> 
> 后面两个问题是今天才出现的，可能是我账号的问题吧。

感谢提供信息，排查后发现确实因为某个不太好解决的参数无法传递导致的。

**Comment by deanxv** [comment]
请参考readme尝试使用该方案解决自动切换模型的问题，如果解决可否给我反馈一下，多谢！
<img width="896" alt="image" src="https://github.com/user-attachments/assets/d176ccc6-8f56-430e-8fa6-528e8228f009" />

**Comment by majesticdragons** [comment]
感谢，添加新变量后模型没被替换了。
