### ISSUE TITLE
PDF对话问题

### ISSUE THREAD

**Issue by Brooktsai** [deanxv/genspark2api#7]
请问一下 不能读pdf是哪里出问题
![76D642FF-9E36-4725-879E-4FF5571D7359](https://github.com/user-attachments/assets/a02766dd-2f95-43ec-acac-11685bcc0ca6)
![IMG_4061](https://github.com/user-attachments/assets/b5924707-04f9-4b29-81ff-1ee4864d458b)

**Comment by deanxv** [comment]
打开genspark官网，找到这条对话记录，查看原始对话记录中文件是否正确上传。

**Comment by Brooktsai** [comment]
这样算有正确上传吗
![IMG_4063](https://github.com/user-attachments/assets/886eed8a-7792-475d-8b20-cb40a17b1ab6)
![8C770430-E2BA-4324-96D7-89CF9A5D5F37](https://github.com/user-attachments/assets/c31f2d34-48c8-4d2e-8e44-b524c1565c3e)

**Comment by deanxv** [comment]
是正常上传的，官网的问题。
