### ISSUE TITLE
Mixture-of-Agents模式的问题

### ISSUE THREAD

**Issue by sd362318** [deanxv/genspark2api#9]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [√ ] 我已确认目前没有类似 issue
+ [√ ] 我已确认我已升级到最新版本
+ [√ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ √] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
触发Mixture-of-Agents模式跟WEB的不太一样，WEB的MOA是3个模型，项目触发的总会有2个模型，这个有没什么方法可以处理，还是说需要项目实现？

**应用场景**
文本对话、润色等使用场景。

**Comment by deanxv** [comment]
这个是官方的触发逻辑，传官网没有的模型就会使用两个模型。至于2api，下个版本也可以改成传递官方没有的模型然后去尝试触发Mixtrue
